path: '/content/drive/MyDrive/cucumber_project2/data/' # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

nc: 1
names: ['leaf']
